### ISSUE TITLE
Whitespace changes broke the build

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#466]
Enter:
    ./configure && make clean && make

./test/patest1.c:129:16: error: incompatible pointer types passing 'FILE *' (aka 'struct __sFILE *') to parameter of type 'const char *'
      [-Werror,-Wincompatible-pointer-types]
        printf(stderr,"Error: No input default device.\n");

Bug introduced in PR #417
This slipped through CI.
