### PR TITLE
Add CI that builds both STATIC and SHARED libraries

### LINKED ISSUE #1093: CMake: CI does not test building shared libs
apparently building shared lib is broken, but we did not know because CI doesn't build it.

see recent discussion on #1085
phil to make a ticket about the breakage

### PR DESCRIPTION
**Pull request by philburk**
Clean the build after the STATIC build.

Fixes #1093

### CODE REVIEW

**Comment by philburk** [comment]
The MinGW build for STATIC is passing:
    
    [ 78%] Linking CXX executable paqa_dither.exe

But the SHARED build is failing with:
```
[ 78%] Linking C executable paqa_dither.exe
[ 78%] Built target patest_enumerate_default_latency
[ 79%] Building C object qa/CMakeFiles/paqa_latency.dir/paqa_latency.c.obj
[ 80%] Building C object qa/loopback/CMakeFiles/paloopback.dir/src/audio_analyzer.c.obj
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/15.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\paqa_dither.dir/objects.a(paqa_dither.c.obj): in function `MeasureAverageConversion':
D:/a/portaudio/portaudio/qa/paqa_dither.c:204:(.text+0x8e): undefined reference to `PaUtil_InitializeTriangularDitherState'
```

So it seems the CI is building with both STATIC and SHARED and the SHARED build is failing. Yay!

**Comment by philburk** [comment]
I tested the fix that is now in #1096 and the CI passed.
So the CI change seems good and the fix seems good.
I then removed the fix so that reviewers can see that the CI is failing, and thus catching the bug in #1094.

**Comment by RossBencina** [comment]
I think you could do this with a single build step with the matrix like this:

```
build:
  strategy:
    matrix:
      PA_BUILD_SHARED_LIBS: [ON, OFF]
      
...

    - name: Configure PortAudio library
      run: cmake

...

      -DPA_BUILD_SHARED_LIBS=${{matrix.PA_BUILD_SHARED_LIBS}}
```

**Comment by philburk** [comment]
Use #1099 instead.
