### PR TITLE
Fix patest1 printf

### LINKED ISSUE #466: Whitespace changes broke the build
Enter:
    ./configure && make clean && make

./test/patest1.c:129:16: error: incompatible pointer types passing 'FILE *' (aka 'struct __sFILE *') to parameter of type 'const char *'
      [-Werror,-Wincompatible-pointer-types]
        printf(stderr,"Error: No input default device.\n");

Bug introduced in PR #417
This slipped through CI.

### PR DESCRIPTION
**Pull request by philburk**
Got changed from fprintf accidentally.

Fixes #466

### CODE REVIEW

File: test/patest1.c [hunk 1]
```diff
@@ -126,7 +126,7 @@ int main(int argc, char* argv[])
 
     inputParameters.device = Pa_GetDefaultInputDevice();    /* default input device */
     if (inputParameters.device == paNoDevice) {
-        printf(stderr,"Error: No input default device.\n");
+        fprintf(stderr,"Error: No input default device.\n");
```
Comment (philburk) [inline test/patest1.c:129]:
```suggestion
        fprintf(stderr, "Error: No input default device.\n");
```

**Review by philburk — COMMENTED** [review]
Should add a space.

**Comment by philburk** [comment]
I am going ahead and merging this because it is a trivial fix for an obvious typo bug.
