### ISSUE TITLE
Ubuntu build fails to find sys/audioio.h

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#653]
The configure script for Ubuntu 18.04 fails because of a missing <sys/audioio.h>

**To Reproduce**
1. Check out latest code on Ubuntu 18.04
2. autoconf
3. ./configure
4. make

**Expected behavior**
Successful build.

**Actual behavior**

libtool: compile:  gcc -c -g -O2 -DPA_LITTLE_ENDIAN -I./include -I./src/common -I./src/os/unix -pthread -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_SYS_SOUNDCARD_H=1 -DHAVE_LINUX_SOUNDCARD_H=1 -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=8 -DHAVE_CLOCK_GETTIME=1 -DHAVE_NANOSLEEP=1 -DPA_USE_ALSA=1 -DPA_USE_AUDIOIO=1 -DPA_USE_JACK=1 -DPA_USE_OSS=1 src/hostapi/audioio/pa_unix_audioio.c  -fPIC -DPIC -o src/hostapi/audioio/.libs/pa_unix_audioio.o
src/hostapi/audioio/pa_unix_audioio.c:46:10: fatal error: sys/audioio.h: No such file or directory
 #include <sys/audioio.h>
          ^~~~~~~~~~~~~~~

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS] Ubuntu
 - OS Version [e.g. 22] 18.04
 - PortAudio version: stable, nightly snapshot (which?), current (please give date and/or Git hash): master
 - If Windows or Linux, which Host API (e.g. WASAPI): default

**Additional context**
Caused by #645

./configure prints:

    checking sys/audioio.h usability... no
    checking sys/audioio.h presence... no
    checking for sys/audioio.h... no

    AudioIO ..................... no

**Comment by raphael10-collab** [comment]
Hhi @philburk !

I'm having the same issue with Ubuntu 24.04  :  

    raphy@raohy:~/portaudio$ cmake -B builddir
    CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 3.5 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- The C compiler identification is GNU 12.3.0
    -- The CXX compiler identification is GNU 14.2.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Checking for module 'jack'
    --   Found jack, version 0.126.0
    -- Found Regex: POSIX regex.h
    -- Found JACK: /usr/lib/x86_64-linux-gnu/libjack.so;/usr/lib/x86_64-linux-gnu/libpthread.a;Regex::regex
    -- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.2.11")
    -- Found OSS: /usr/include/x86_64-linux-gnu
    -- Looking for sys/audioio.h
    -- Looking for sys/audioio.h - not found
    -- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
    -- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so (found suitable version "16.1.0", minimum required is "1.0.0")
    -- Checking for module 'sndio'
    --   Found sndio, version 1.9.0
    -- Configuring done (0.5s)
    -- Generating done (0.0s)
    -- Build files have been written to: /home/raphy/portaudio/builddir
    raphy@raohy:~/portaudio$ 
    raphy@raohy:~/portaudio$ cmake --build builddir/
    [  5%] Building C object CMakeFiles/portaudio.dir/src/common/pa_allocation.c.o
    [ 10%] Building C object CMakeFiles/portaudio.dir/src/common/pa_converters.c.o
    [ 15%] Building C object CMakeFiles/portaudio.dir/src/common/pa_cpuload.c.o
    [ 20%] Building C object CMakeFiles/portaudio.dir/src/common/pa_debugprint.c.o
    [ 25%] Building C object CMakeFiles/portaudio.dir/src/common/pa_dither.c.o
    [ 30%] Building C object CMakeFiles/portaudio.dir/src/common/pa_front.c.o
    [ 35%] Building C object CMakeFiles/portaudio.dir/src/common/pa_process.c.o
    [ 40%] Building C object CMakeFiles/portaudio.dir/src/common/pa_ringbuffer.c.o
    [ 45%] Building C object CMakeFiles/portaudio.dir/src/common/pa_stream.c.o
    [ 50%] Building C object CMakeFiles/portaudio.dir/src/common/pa_trace.c.o
    [ 55%] Building C object CMakeFiles/portaudio.dir/src/hostapi/jack/pa_jack.c.o
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c: In function ‘BuildDeviceList’:
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:523:5: error: unknown type name ‘regex_t’; did you mean ‘gregset_t’?
      523 |     regex_t port_regex;
          |     ^~~~~~~
          |     gregset_t
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:532:18: warning: implicit declaration of function ‘regcomp’ [-Wimplicit-function-declaration]
      532 |     ASSERT_CALL( regcomp( &port_regex, "^[^:]*", REG_EXTENDED ), 0 );
          |                  ^~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:118:20: note: in definition of macro ‘ASSERT_CALL’
      118 |         int err = (expr); \
          |                    ^~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:532:50: error: ‘REG_EXTENDED’ undeclared (first use in this function)
      532 |     ASSERT_CALL( regcomp( &port_regex, "^[^:]*", REG_EXTENDED ), 0 );
          |                                                  ^~~~~~~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:118:20: note: in definition of macro ‘ASSERT_CALL’
      118 |         int err = (expr); \
          |                    ^~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:532:50: note: each undeclared identifier is reported only once for each function it appears in
      532 |     ASSERT_CALL( regcomp( &port_regex, "^[^:]*", REG_EXTENDED ), 0 );
          |                                                  ^~~~~~~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:118:20: note: in definition of macro ‘ASSERT_CALL’
      118 |         int err = (expr); \
          |                    ^~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:558:9: error: unknown type name ‘regmatch_t’
      558 |         regmatch_t match_info;
          |         ^~~~~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:564:18: warning: implicit declaration of function ‘regexec’ [-Wimplicit-function-declaration]
      564 |         UNLESS( !regexec( &port_regex, port, 1, &match_info, 0 ), paInternalError );
          |                  ^~~~~~~
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:102:14: note: in definition of macro ‘UNLESS’
      102 |         if( (expr) == 0 ) \
          |              ^~~~
    In file included from /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:54:
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:26: error: request for member ‘rm_eo’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                          ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:45: error: request for member ‘rm_so’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                                             ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:26: error: request for member ‘rm_eo’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                          ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:565:45: error: request for member ‘rm_so’ in something not a structure or union
      565 |         assert(match_info.rm_eo - match_info.rm_so <= jack_client_name_size());
          |                                             ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:566:51: error: request for member ‘rm_so’ in something not a structure or union
      566 |         memcpy( tmp_client_name, port + match_info.rm_so,
          |                                                   ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:567:27: error: request for member ‘rm_eo’ in something not a structure or union
      567 |                 match_info.rm_eo - match_info.rm_so );
          |                           ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:567:46: error: request for member ‘rm_so’ in something not a structure or union
      567 |                 match_info.rm_eo - match_info.rm_so );
          |                                              ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:568:35: error: request for member ‘rm_eo’ in something not a structure or union
      568 |         tmp_client_name[match_info.rm_eo - match_info.rm_so] = '\0';
          |                                   ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:568:54: error: request for member ‘rm_so’ in something not a structure or union
      568 |         tmp_client_name[match_info.rm_eo - match_info.rm_so] = '\0';
          |                                                      ^
    /home/raphy/portaudio/src/hostapi/jack/pa_jack.c:695:5: warning: implicit declaration of function ‘regfree’; did you mean ‘free’? [-Wimplicit-function-declaration]
      695 |     regfree( &port_regex );
          |     ^~~~~~~
          |     free
    gmake[2]: *** [CMakeFiles/portaudio.dir/build.make:216: CMakeFiles/portaudio.dir/src/hostapi/jack/pa_jack.c.o] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/portaudio.dir/all] Error 2



What do I have to do in order to solve it?
